
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team01-s25-11
owner: ucsb-cs156-s25
repo_name: team01-s25-11
pull_requests: [{"author":{"id":"U_kgDOCRaVBA","is_bot":false,"login":"luismendoza25","name":"Luis Mendoza"},"headRefName":"lm-HelpRequest-delete","number":59,"title":"lm-helpRequestDelete","url":"https://github.com/ucsb-cs156-s25/team01-s25-11/pull/59"},{"author":{"id":"U_kgDOCRaVBA","is_bot":false,"login":"luismendoza25","name":"Luis Mendoza"},"headRefName":"lm-addPut","number":58,"title":"lm-Add 'PUT' for Help Request table","url":"https://github.com/ucsb-cs156-s25/team01-s25-11/pull/58"},{"author":{"id":"U_kgDOCRaVBA","is_bot":false,"login":"luismendoza25","name":"Luis Mendoza"},"headRefName":"lm-getSingle","number":57,"title":"lm-Add('GET') for single record in Help Request table","url":"https://github.com/ucsb-cs156-s25/team01-s25-11/pull/57"},{"author":{"id":"U_kgDOB5HCgg","is_bot":false,"login":"aaasami","name":"Shuang"},"headRefName":"sl-create-articles-controller","number":56,"title":"sl - create Articles Controller, add GET/all and POST methods","url":"https://github.com/ucsb-cs156-s25/team01-s25-11/pull/56"}]
