
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team01-s25-11
owner: ucsb-cs156-s25
repo_name: team01-s25-11
pull_requests: [{"author":{"id":"U_kgDOCM7m9w","is_bot":false,"login":"jonahso","name":""},"headRefName":"js-MenuItemReview-delete","number":71,"title":"added delete method and tests for menu item review ","url":"https://github.com/ucsb-cs156-s25/team01-s25-11/pull/71"},{"author":{"id":"U_kgDOCM7m9w","is_bot":false,"login":"jonahso","name":""},"headRefName":"js-MenuItemReview-put","number":70,"title":"added edit method and tests for menu item review ","url":"https://github.com/ucsb-cs156-s25/team01-s25-11/pull/70"},{"author":{"id":"U_kgDOCM7m9w","is_bot":false,"login":"jonahso","name":""},"headRefName":"js-MenuItemReview-get","number":69,"title":"added get method and test for menu item review","url":"https://github.com/ucsb-cs156-s25/team01-s25-11/pull/69"},{"author":{"id":"U_kgDOCM7m9w","is_bot":false,"login":"jonahso","name":""},"headRefName":"js-MenuItemReview-Controller","number":68,"title":"created menu item review controller, added get and post","url":"https://github.com/ucsb-cs156-s25/team01-s25-11/pull/68"}]
