
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team01-s25-11
owner: ucsb-cs156-s25
repo_name: team01-s25-11
pull_requests: [{"author":{"id":"MDQ6VXNlcjUzMjM2OTYx","is_bot":false,"login":"Wendy192837","name":""},"headRefName":"Wendy-ReqRequestTable","number":62,"title":"ws - added database tables","url":"https://github.com/ucsb-cs156-s25/team01-s25-11/pull/62"},{"author":{"id":"U_kgDOB5HCgg","is_bot":false,"login":"aaasami","name":"Shuang"},"headRefName":"sl-articles-get","number":61,"title":"sl - add GET and tests on articles","url":"https://github.com/ucsb-cs156-s25/team01-s25-11/pull/61"},{"author":{"id":"U_kgDOCM7m9w","is_bot":false,"login":"jonahso","name":""},"headRefName":"js-MenuItemReview-create-db","number":60,"title":"Js menu item review create db","url":"https://github.com/ucsb-cs156-s25/team01-s25-11/pull/60"},{"author":{"id":"U_kgDOCRaVBA","is_bot":false,"login":"luismendoza25","name":"Luis Mendoza"},"headRefName":"lm-HelpRequest-delete","number":59,"title":"lm-helpRequestDelete","url":"https://github.com/ucsb-cs156-s25/team01-s25-11/pull/59"},{"author":{"id":"U_kgDOCRaVBA","is_bot":false,"login":"luismendoza25","name":"Luis Mendoza"},"headRefName":"lm-addPut","number":58,"title":"lm-Add 'PUT' for Help Request table","url":"https://github.com/ucsb-cs156-s25/team01-s25-11/pull/58"}]
