
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team01-s25-11
owner: ucsb-cs156-s25
repo_name: team01-s25-11
pull_requests: [{"author":{"id":"MDQ6VXNlcjUzMjM2OTYx","is_bot":false,"login":"Wendy192837","name":""},"headRefName":"ws-add_delete_endpoint","number":67,"title":"ws - add delete endpoint","url":"https://github.com/ucsb-cs156-s25/team01-s25-11/pull/67"},{"author":{"id":"MDQ6VXNlcjUzMjM2OTYx","is_bot":false,"login":"Wendy192837","name":""},"headRefName":"ws-add_put_endpoint","number":66,"title":"ws - added put tests and controller","url":"https://github.com/ucsb-cs156-s25/team01-s25-11/pull/66"}]
